import os
import sys

os.system('title 돌리와 도트가 젤 좋아 - Setup')
os.system('color 03')
os.system('mode con cols=50 lines=10')
os.system('cls')

print('\n > 처음 실행인가요? ', end='')
apc = input()
if apc == '1':
    os.system('cls')
    print('\n > 현재 Python 버전 : ' + sys.version)
    print('\n > PyAudio 파일명을 입력해 주세요 : ', end='')
    aPy = input()
    os.system('cls')
    print('\n > pip 설치 시작')
    op = 'pip install '
    os.system(op + 'pyserial')
    os.system('cls')
    print('\n > pip 설치 시작')
    print(' > pyserial 설치 완료')
    os.system(op + 'SpeechRecognition')
    os.system('cls')
    print('\n > pip 설치 시작')
    print(' > pyserial 설치 완료')
    print(' > SpeechRecognition 설치 완료')
    os.system(op + 'gTTS')
    os.system('cls')
    print('\n > pip 설치 시작')
    print(' > pyserial 설치 완료')
    print(' > SpeechRecognition 설치 완료')
    print(' > gTTS 설치 완료')
    os.system(op + aPy + '.whl')
    os.system('cls')
    print('\n > pip 설치 시작')
    print(' > pyserial 설치 완료')
    print(' > SpeechRecognition 설치 완료')
    print(' > gTTS 설치 완료')
    print(' > PyAudio 설치 완료')
    print(' > pip 설치 완료 \n\n > ', end='')
    os.system('pause')
elif apc == '2':
    op = 'pip uninstall '
    print(' > 현재 Python 버전 : ' + sys.version)
    print(' > PyAudio 파일명을 입력해 주세요 : ', end='')
    aPy = input()
    os.system(op + 'pyserial')
    os.system(op + 'SpeechRecognition')
    os.system(op + 'gTTS')
    os.system(op + aPy + '.whl')
    os.system('cls')
    print('\n\n > 제거완료 \n\n > ', end='')
    os.system('pause')
